query($take: Int, $skip: Int, $province: String, $city: String, $type: String, $categoryIdsByOr: String, $categoryId: String) {
  companies(take: $take, skip: $skip, province: $province, city: $city, type: $type, categoryIdsByOr: $categoryIdsByOr, categoryId: $categoryId) {
    items {
      id
      logoUrl
      brandName
      notAllPass
      verifyStatus
      isIndividual
      hasProducts
      hasSites
      hasPublishedSites
      residentCountry
      residentProvince
    }
  }
}